---
- hosts: localhost
  become: true
  vars:
    - docker_users:
        - sshah
    - nvm_node_version: "14.5.0"
    - nvm_user_name: "sshah"
    - nvm_install_globally: ['yarn']
    - users:
        - username: sshah
          visual_studio_code_extensions:
            - CoenraadS.bracket-pair-colorizer
            - dbaeumer.vscode-eslint 
            - dracula-theme.theme-dracula
            - eamodio.gitlens
            - esbenp.prettier-vscode
            - ms-python.python
            - redhat.vscode-yaml
            - streetsidesoftware.code-spell-checker
            - vscodevim.vim
            - zhuangtongfa.Material-theme
  roles:
    - role: gantsign.visual-studio-code
    - role: gantsign.visual-studio-code-extensions
    - role: geerlingguy.docker
    - role: grzegorznowak.nvm_node
    - role: oefenweb.slack
    - role: webarchitect609.google_chrome
  tasks:
    - include_tasks: tasks/os-packages.yml
      tags: always

