---
- name: Include OS Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Install OS Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_packages }}"

- name: Install Snaps
  snap:
    name: "{{ item }}"
    state: present
  with_items: "{{ snaps }}"
